### ISSUE TITLE
For demo.py : "RuntimeError: CUDA out of memory." 

### ISSUE THREAD

**Issue by developer-young** [serend1p1ty/SeqNet#13]
Hello,I use the trained model to run demo.py,it passes one gallery image and throws the error.
```shell
Processing demo_imgs/gallery-2.jpg
Traceback (most recent call last):
  File "demo.py", line 89, in <module>
    main(args)
  File "demo.py", line 69, in main
    gallery_output = model(gallery_img)[0]
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/workspace/SeqNet/models/seqnet.py", line 132, in forward
    return self.inference(images, targets, query_img_as_gallery)
  File "/home/ubuntu/workspace/SeqNet/models/seqnet.py", line 107, in inference
    features = self.backbone(images.tensors)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/workspace/SeqNet/models/resnet.py", line 27, in forward
    feat = super(Backbone, self).forward(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/models/resnet.py", line 113, in forward
    out = self.bn3(out)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/batchnorm.py", line 131, in forward
    return F.batch_norm(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/functional.py", line 2014, in batch_norm
    return torch.batch_norm(
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 7.80 GiB total capacity; 6.81 GiB already allocated; 1.38 MiB free; 6.89 GiB reserved in total by PyTorch)
```
Can you give some suggestions to avoid "OOM"?

**Comment by developer-young** [comment]
I have sloved it. The gradient is unnecessary in the inference stage of the model.
```python
with torch.no_grad():
    output = model(input)
```

**Comment by serend1p1ty** [comment]
Sorry to reply late. I will fix the small bug, or maybe you want to pull a request.
