### ISSUE TITLE
Problems running demo.py

### ISSUE THREAD

**Issue by Svithjod** [serend1p1ty/SeqNet#29]
Hi, I was running the demo code of seqnet:
`python demo.py --cfg ~/checkpoints/seqnet/config.yaml --ckpt ~/checkpoints/seqnet/epoch_17.pth`

but I got the following error:

Traceback (most recent call last):
  File "demo.py", line 89, in <module>
    main(args)
  File "demo.py", line 63, in main
    query_feat = model(query_img, query_target)[0]
  File "/home/mmmm/miniconda3/envs/seqnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mmmm/repo/SeqNet/models/seqnet.py", line 134, in forward
    return self.inference(images, targets, query_img_as_gallery)
  File "/home/mmmm/repo/SeqNet/models/seqnet.py", line 117, in inference
    box_features = self.roi_heads.box_roi_pool(features, boxes, images.image_sizes)
  File "/home/mmmm/miniconda3/envs/seqnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mmmm/miniconda3/envs/seqnet/lib/python3.7/site-packages/torchvision/ops/poolers.py", line 141, in forward
    sampling_ratio=self.sampling_ratio
  File "/home/mmmm/miniconda3/envs/seqnet/lib/python3.7/site-packages/torchvision/ops/roi_align.py", line 70, in roi_align
    return _RoIAlignFunction.apply(input, rois, output_size, spatial_scale, sampling_ratio)
  File "/home/mmmm/miniconda3/envs/seqnet/lib/python3.7/site-packages/torchvision/ops/roi_align.py", line 25, in forward
    output_size[0], output_size[1], sampling_ratio)
RuntimeError: Expected tensor for argument #1 'input' to have the same type as tensor for argument #2 'rois'; but type Variable[CUDAFloatType] does not equal Variable[CUDALongType] (while checking arguments for ROIAlign_forward_cuda) (checkSameType at /pytorch/aten/src/ATen/TensorUtils.cpp:140)

So far I had no idea what caused this error, could you help me with this problem? Thx a lot.

**Comment by serend1p1ty** [comment]
Try to downgrade your PyTorch/TorchVision. PyTorch 1.3-1.8 should be ok.

**Comment by Svithjod** [comment]
Hi, thx for your reply, I was using PyTorch 1.2.0 and TorchVision 0.4.0 as in requirements, should I upgrade them to PyTorch 1.3+ and corresponding TorchVision version?

**Comment by Svithjod** [comment]
Thank you,I got this done by upgrading my PyTorch and TorchVision to proper version.

**Comment by serend1p1ty** [comment]
It's a little strange, because I used PyTorch=1.2.0 & TorchVision=0.4.0 before.

**Comment by Svithjod** [comment]
Not sure what caused this problem, I’m currently using pytorch==1.5.1+cu101 and torchvision==0.6.1+cu101, it works perfectly smooth.
